spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chess_com_database
    username: postgres
    password: hvorosttina17
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        order_inserts: true
        jdbc:
          batch_size: 20
    open-in-view: true
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html